export const PAGES_MENU = [
  {
    path:'pages',
    children:[
      {
        path:'info',
        data:{
          menu:{
            title:'information',
            iconfont:'icon-info',
            selected:false,
            expanded:false,
            order:0
          }
        }
      }
    ]
  }
];
